module.exports = {
  POSTCODE_SUCCESS : "N11 3PW",
  POSTCODE_NOT_EXIST : "N11 3PQ",
  POSTCODE_INVALID : "123123",
  
  RADIUS_SUCCESS : 1000,
  RADIUS_OVER_RANGE : 20000,
  RADIUS_UNDER_RANGE : -1,
  RADIUS_INVALID_VALUE : "aaaa",
  
  STORE_NAME_SUCCESS : "Hendon",
  STORE_NAME_NOT_EXIST : "Hendndnd"
}